apiVersion: v1
kind: Service
metadata:
  name: neo4j-svc
spec:
  ports:
    - port: 7474
      targetPort: 7474
      name: http
    - port: 7687
      targetPort: 7687
      name: bolt
  selector:
    app: neo4j
    component: neo4j
  type: NodePort
  externalIPs:
  - 172.24.0.10
